#!/bin/bash

CONFIG_FILES=(
    "floras_ru_dev.yaml"
    "floras_ru_test.yaml"
    "floras_es_dev.yaml"
    "floras_es_test.yaml"
    "floras_de_dev.yaml"
    "floras_de_test.yaml"
    "floras_fr_dev.yaml"
    "floras_fr_test.yaml"
    "floras_it_dev.yaml"
    "floras_it_test.yaml"
    "floras_id_dev.yaml"
    "floras_id_test.yaml"
    "floras_ja_dev.yaml"
    "floras_ja_test.yaml"
    "floras_pt_dev.yaml"
    "floras_pt_test.yaml"
    "floras_tr_dev.yaml"
    "floras_tr_test.yaml"
    "floras_pl_dev.yaml"
    "floras_pl_test.yaml"
    "floras_zh_dev.yaml"
    "floras_zh_test.yaml"
    "floras_nl_dev.yaml"
    "floras_nl_test.yaml"
    "floras_hu_dev.yaml"
    "floras_hu_test.yaml"
    "floras_eu_dev.yaml"
    "floras_eu_test.yaml"
    "floras_hi_dev.yaml"
    "floras_hi_test.yaml"
    "floras_vi_dev.yaml"
    "floras_vi_test.yaml"
    "floras_fi_dev.yaml"
    "floras_fi_test.yaml"
    "floras_uk_dev.yaml"
    "floras_uk_test.yaml"
    "floras_el_dev.yaml"
    "floras_el_test.yaml"
    "floras_ro_dev.yaml"
    "floras_ro_test.yaml"
    "floras_ca_dev.yaml"
    "floras_ca_test.yaml"
    "floras_cs_dev.yaml"
    "floras_cs_test.yaml"
    "floras_th_dev.yaml"
    "floras_th_test.yaml"
    "floras_et_dev.yaml"
    "floras_et_test.yaml"
    "floras_ms_dev.yaml"
    "floras_ms_test.yaml"
    "floras_fa_dev.yaml"
    "floras_fa_test.yaml"
    "floras_ta_dev.yaml"
    "floras_ta_test.yaml"
    "floras_sk_dev.yaml"
    "floras_sk_test.yaml"
    "floras_sl_dev.yaml"
    "floras_sl_test.yaml"
    "floras_hr_dev.yaml"
    "floras_hr_test.yaml"
    "floras_da_dev.yaml"
    "floras_da_test.yaml"
    "floras_sr_dev.yaml"
    "floras_sr_test.yaml"
    "floras_la_dev.yaml"
    "floras_la_test.yaml"
    "floras_ar_dev.yaml"
    "floras_ar_test.yaml"
    "floras_uz_dev.yaml"
    "floras_uz_test.yaml"
    "floras_bg_dev.yaml"
    "floras_bg_test.yaml"
    "floras_sv_dev.yaml"
    "floras_sv_test.yaml"
    "floras_ur_dev.yaml"
    "floras_ur_test.yaml"
    "floras_gl_dev.yaml"
    "floras_gl_test.yaml"
    "floras_bn_dev.yaml"
    "floras_bn_test.yaml"
    "floras_bs_dev.yaml"
    "floras_bs_test.yaml"
    "floras_cy_dev.yaml"
    "floras_cy_test.yaml"
    "floras_ku_dev.yaml"
    "floras_ku_test.yaml"
    "floras_ky_dev.yaml"
    "floras_ky_test.yaml"
    "floras_ka_dev.yaml"
    "floras_ka_test.yaml"
    "floras_az_dev.yaml"
    "floras_az_test.yaml"
    "floras_mi_dev.yaml"
    "floras_mi_test.yaml"
)

# whisper does not support esperanto (eo)
#     "floras_eo_dev.yaml"
#    "floras_eo_test.yaml"

base_cmd="python -m tools.evaluate --serial 995 --warmup_steps 2 --max_eval_samples 4 --batch_size 2 --model_id openai/whisper-tiny"

# Iterate through all combinations
for cfg in "${CONFIG_FILES[@]}"; do
    # Execute the command
    cmd="$base_cmd --config configs/datasets/long_ml/$cfg"
    echo "$cmd"
    $cmd
done
